#!/usr/bin/env ruby
#--
# Copyright 2006 by Chad Fowler, Rich Kilmer, Jim Weirich and others.
# All rights reserved.
# See LICENSE.txt for permissions.
#++

require 'rubygems'
require 'rubygems/gem_runner'
require 'rubygems/exceptions'

required_version = Gem::Requirement.new ">= 1.8.7"

unless required_version.satisfied_by? Gem.ruby_version then
  abort "Expected Ruby Version #{required_version}, is #{Gem.ruby_version}"
end

args = ARGV.clone

trap("TERM") do
end

begin
  puts "Running Gem using TUF proxy "
  webpy_proxy = fork do
    exec "tuf-proxy.py"
  end
  Gem::GemRunner.new.run args
rescue Gem::SystemExitException => e
  exit e.exit_code
ensure
  Process.kill "TERM", -Process.getpgid(webpy_proxy)
  Process.wait webpy_proxy
end

